-- ============================================
-- Script de Base de Datos: Traductor Emberá-Español
-- ============================================
-- Este script crea las tablas necesarias e inserta
-- el diccionario completo de 269 palabras Emberá-Español
-- 
-- Base de datos: PostgreSQL
-- Encoding: UTF-8
-- ============================================

-- Habilitar extensión para generar UUIDs (necesario para tabla users)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Crear tabla del diccionario
CREATE TABLE IF NOT EXISTS diccionario (
    id SERIAL PRIMARY KEY,
    espanol TEXT NOT NULL,
    embera TEXT NOT NULL
);

-- Crear tabla de usuarios (opcional - para autenticación futura)
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

-- Limpiar datos existentes (opcional - comentar si no desea limpiar)
-- TRUNCATE TABLE diccionario RESTART IDENTITY CASCADE;

-- ============================================
-- Insertar palabras del diccionario (269 palabras)
-- ============================================

INSERT INTO diccionario (espanol, embera) VALUES
('adelante', 'na'),
('adios o hasta luego', 'wãbu'),
('adiós', 'arambaré'),
('agua', 'juí'),
('aguacate', 'bego'),
('aguila', 'eumiajo'),
('aji', 'phida'),
('alfondo', 'edu'),
('amaca', 'jiraba'),
('amarillo', 'parúa'),
('amigo', 'aramá'),
('amor', 'dedí'),
('araña', 'torema'),
('araña', 'pᵾgᵾrᵾ'),
('arbol', 'pakuru'),
('arbol de pan', 'phantha'),
('ardilla', 'bᵾtᵾ'),
('ardilla', 'chidima'),
('arena', 'ĩpᵾ'),
('arrastrar', 'urrajui'),
('arriba', 'ᵾta'),
('ayer', 'nueda'),
('azotea', 'barawa'),
('azul', 'azurá'),
('bailar', 'kutú'),
('barranquero', 'jᵾdu'),
('beber', 'juíkó'),
('bija o achiote', 'kãchi'),
('blanco', 'chirá'),
('boca', 'ithae'),
('bonito', 'dosúa'),
('bueno', 'warrá'),
('buenos días', 'jinú parásida'),
('buscar', 'jurrui'),
('buya', 'ororoa'),
('cabello', 'Puda'),
('cabeza', 'poro'),
('caldero', 'kuguru'),
('caminar', 'purá'),
('camino', 'o'),
('canasta', 'jamara'),
('canasta', 'ẽ'),
('canoa', 'purú'),
('canoa y champa', 'janpha'),
('cantar', 'imakó'),
('caracol', 'korogo'),
('casa', 'bé'),
('caña', 'chiaso'),
('cedro', 'ogo'),
('cerdo', 'china'),
('cesta', 'warrá'),
('chaquira', 'kᵾrrᵾjᵾma'),
('chochora', 'ochorro'),
('chontaduro', 'jẽa'),
('chontaduro', 'jẽa'),
('cielo', 'trupá'),
('cinco', 'atubí'),
('coco', 'koko'),
('cocodrilo', 'kore'),
('colibri', 'ĩpisu'),
('collar', 'chaquira'),
('colmillo', 'nekida'),
('comer', 'amakó'),
('comida', 'amá'),
('corazón', 'aré'),
('correr', 'phirai'),
('cortar', 'thumabu'),
('costilla', 'orro'),
('cuatro', 'aró'),
('cucaracha', 'kẽperre'),
('cuello', 'ochiru'),
('cuerpo', 'kakua'),
('cuervo', 'tophe'),
('curar', 'jaíkó'),
('deyerbar -rosar', 'pui'),
('dias', 'idi'),
('dientes', 'kida'),
('dolor', 'kukú'),
('dormir', 'drabé'),
('dos', 'ombí'),
('emvuelto', 'beka'),
('enbuelto', 'beka'),
('enfermedad', 'dedekó'),
('escalera', 'tume'),
('esconder', 'mirũi'),
('esconder', 'merui'),
('ese', 'naᵾgʉ'),
('espacio', 'bari'),
('espina', 'ᵾrᵾ'),
('espina', 'urua'),
('estabien', 'piaka'),
('este', 'nama'),
('estoy bien', 'biai'),
('estoy escuchando', 'ᵾri nᵾbᵾa'),
('estoy parado', 'uphanᵾa'),
('estrella', 'dedebáta'),
('estrellas', 'chintau'),
('fallecido', 'nepasia'),
('familia', 'purúm'),
('feliz', 'anambí'),
('flauta', 'dedé'),
('flor', 'dosúara'),
('frito', 'jʉrʉi'),
('frutas', 'netha'),
('frutas', 'nejõ'),
('frutas', 'netha'),
('fruto', 'amabá'),
('fuego', 'ñudá'),
('gallina o gallo', 'etherre'),
('gallinaso', 'ãgosothorror'),
('gato', 'michi'),
('golper', 'poya'),
('gracias', 'benkruá'),
('grande', 'bedabú'),
('guacamaya', 'pagara'),
('guacuco', 'gorroma'),
('guacuco', 'jũphe'),
('guadua', 'chogoro'),
('guagua', 'pẽrora'),
('guardar', 'kũagai'),
('guasca o cabuya', 'jᵾkara'),
('guayaba', 'phorijõ'),
('gusano', 'karaga'),
('hablar', 'peresé'),
('hacha', 'tsagara'),
('hermana', 'bedama'),
('hermano', 'bedé'),
('hermanos', 'chapa'),
('hervir', 'chui'),
('hija', 'chiama'),
('hijo', 'chiá'),
('hoja', 'drabí'),
('hojas', 'ketua'),
('hola', 'panabá'),
('hombre', 'waimbía'),
('hombtre', 'ache'),
('hueco', 'uria'),
('iguana', 'ophoa'),
('jagua', 'kiphara'),
('jugar', 'jemenei'),
('lampara', 'ĩpira'),
('lazo', 'jᵾkara'),
('lechusa', 'põpõra'),
('leña', 'thᵾpᵾ onoko'),
('llorar', 'jẽai'),
('lluvia', 'kurí'),
('locion', 'kera'),
('lombris', 'mokitha'),
('loro', 'kare'),
('loro', 'kare'),
('lulo', 'lulojõ'),
('luna', 'akará'),
('madre', 'umá'),
('maiz', 'pe'),
('malo', 'warrá kudé'),
('mano', 'jᵾwa'),
('mapana', 'jẽpha'),
('mapana x', 'bʉrrʉ'),
('mar', 'phusa'),
('mariposas', 'pagapaga'),
('martin pescador', 'ãsapida'),
('mayor', 'napema'),
('medicina', 'jaí'),
('mensaje', 'nepᵾra'),
('mi cuñada', 'mᵾ añure'),
('micuro', 'paũ'),
('mio', 'mᵾre'),
('mojar', 'begeai'),
('montaña', 'wadó'),
('morcielago', 'ĩkata'),
('muejer', 'wẽra'),
('muerte', 'dedé'),
('mujer', 'waimbíama'),
('naranja', 'larajõ'),
('naris', 'kenbu'),
('naris', 'kẽpᵾ'),
('nariz', 'kepu'),
('negro', 'kisirá'),
('niña', 'chiéma'),
('niño', 'chié'),
('no', 'kudé'),
('no esta', 'ne'),
('olla', 'phana'),
('ondo', 'napᵾa'),
('ormiga', 'jẽsera'),
('oscuro', 'phaima'),
('padre', 'akóre'),
('pajararo', 'ĩge'),
('palma', 'arra'),
('pato', 'phatu'),
('pavo', 'thusi'),
('paz', 'anambía'),
('pequeño', 'chichiná'),
('perica', 'bᵾcha'),
('periquito', 'kerrekerre'),
('perro', 'usa'),
('persona', 'ẽperarã'),
('pescado', 'beta'),
('pez', 'namá'),
('pichinde', 'bidua'),
('piedra', 'mogara'),
('piso', 'kᵾdaphõ'),
('piña', 'chijõ'),
('platanillo', 'jãga'),
('platano', 'mananaphata'),
('platano', 'phata'),
('pueblo', 'phuru'),
('pueblos', 'phuru'),
('pájaro', 'chipía'),
('rana', 'wᵾrᵾkᵾkᵾ'),
('raton', 'kado'),
('raíz', 'aká'),
('recoger', 'pei'),
('recoger', 'phei'),
('remo', 'purubá'),
('renacuajo', 'baupa'),
('repirar', 'ᵾñapade'),
('risa', 'iphida bᵾa'),
('rojo', 'kiridá'),
('río', 'dokabí'),
('sabalo', 'ãpharra'),
('sabio', 'jaipana'),
('salero', 'ikorokoro'),
('saltar', 'jedai'),
('sancudo', 'jeda'),
('sano', 'warrá bedé'),
('sanpedro', 'phãrara'),
('sapo', 'pokorro'),
('sardina', 'amachichi'),
('selva', 'párra'),
('semilla', 'ombira'),
('sentar', 'chumei'),
('serbatana', 'ugu'),
('serbatana', 'ugu'),
('sigueña', 'õko'),
('sol', 'bedá'),
('solo', 'iduba'),
('sorar o deyerbar', 'bᵾi'),
('sí', 'maí'),
('tambor', 'bedabá'),
('tatabro', 'pidoe'),
('tatabro o saino', 'pidoepa'),
('tender', 'pai'),
('tender', 'thonoga'),
('tierra', 'badá'),
('tigre', 'imama'),
('tirar o tirelo', 'bathai'),
('tirar o tirelo', 'phathai'),
('tortola', 'uma'),
('traer', 'enei'),
('tres', 'kemá'),
('trigrillo', 'ᵾriᵾri'),
('triste', 'bedé kudé'),
('tronco', 'onoko'),
('tucan', 'bichi'),
('uno', 'pokóra'),
('uña', 'pichiwi'),
('venado', 'begi'),
('verano', 'phoa'),
('verde', 'debá'),
('vi-vio-viste', 'unusia'),
('vida', 'bedé'),
('viento', 'burrú'),
('yarumo', 'eporro'),
('yo', 'mᵾa'),
('yo', 'mᵾ'),
('yo', 'mᵾ'),
('zorro', 'jojoma'),
('árbol', 'warra');

-- ============================================
-- Verificar instalación
-- ============================================

-- Contar palabras insertadas (debe ser 269)
SELECT COUNT(*) as total_palabras FROM diccionario;

-- Mostrar algunas palabras de ejemplo
SELECT * FROM diccionario LIMIT 10;

-- ============================================
-- Script completado exitosamente
-- ============================================
-- 
-- Próximos pasos:
-- 1. Configurar las variables de entorno de conexión a la base de datos
-- 2. Asegurar que PostgreSQL está corriendo
-- 3. Ejecutar el servidor de la aplicación
--
-- Para ejecutar este script:
-- psql -U tu_usuario -d nombre_base_datos -f database_setup.sql
--
-- O desde línea de comandos PostgreSQL:
-- \i database_setup.sql
-- ============================================
